name: Release - Docker Image CI

on:
  release:
    branches: [ master ]
    types: [ published ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
#      - name: "Print result"
#        run: |
#          echo "id: ${{ steps.last_release.outputs.id }}"
#          echo "name: ${{ steps.last_release.outputs.name }}"
#          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
#          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
#          echo "draft: ${{ steps.last_release.outputs.draft }}"
#          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            vinanrra/satisfactory-server:latest,vinanrra/satisfactory-server:${{ steps.last_release.outputs.tag_name }}
